apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: node-hello-world
  name: node-hello-world
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-hello-world
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: node-hello-world
    spec:
      containers:
      - image: docker.io/gabrielsousabrax/blite-node-hell-world
        name: blite-node-hell-world
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: node-hello-world-svc
spec:
  type: NodePort
  selector:
    app: node-hello-world
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30001